import { sum } from "./utils/maths";
import { mul } from "./utils/maths";
import "./css/style.css";
import jsonContent from "./model/notes.json";
import textContent from "./utils/test.txt";
console.log("hello");
console.log("sum:", sum(2, 4));
console.log("mul:", mul(2, 4));
console.log(jsonContent);
console.log(textContent);
